# Denarius - Snapcraft Build - Known to build in Ubuntu 18.04+ - WIP Currently as of Denarius v3.3.8.5
# https://denarius.io
# https://github.com/carsenk/denarius
# By Carsen Klock
name: denarius
version: '3.3.8.5'
summary: Denarius
description: |
  An open source hybrid cryptocurrency called Denarius, which features Fortuna Stakes (Masternodes), Staking, Mining, Multisig, and much more!
icon: src/qt/res/icons/denarius_icon.png

grade: devel
confinement: classic

apps:
  denarius:
    command: desktop-launch $SNAP/usr/local/bin/Denarius
    plugs: [network, network-bind, unity7]

parts:
  denarius:
    after: [desktop-qt5]
    plugin: qmake
    qt-version: qt5
    source: https://github.com/carsenk/denarius.git
    build-packages:
      - g++
      - unzip
      - wget
      - jq
      - build-essential
      - apt-transport-https
      - zlib1g-dev
      - libdb++-dev
      - libboost-all-dev
      - libqrencode-dev
      - libminiupnpc-dev
      - libevent-dev
      - libssl-dev
      - libtool
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - qt5-default
      - qtbase5-dev-tools
    override-build: |
      echo "Downgrading OpenSSL to 1.0.1j"
      sudo wget http://www.openssl.org/source/openssl-1.0.1j.tar.gz
      sudo tar -xzvf openssl-1.0.1j.tar.gz
      cd openssl-1.0.1j
      sudo ./config
      sudo make
      sudo make depend
      sudo make install
      sudo ln -sf /usr/local/ssl/bin/openssl `which openssl`
      echo "Creating ~/denarius dir and denarius.conf"
      sudo mkdir ~/.denarius
      sudo chmod +x ~/.denarius
      sudo chmod -R 777 ~/.denarius
      echo "Populating denarius.conf"
      sudo printf "nativetor=0\naddnode=denarius.host\naddnode=denarius.win\naddnode=denarius.pro\naddnode=triforce.black" > ~/.denarius/denarius.conf
      echo "Grabbing Latest Chaindata"
      cd ~/.denarius
      sudo rm -rf database txleveldb smsgDB
      sudo wget http://github.com/carsenk/denarius/releases/download/v3.3.7/chaindata1799510.zip
      sudo unzip chaindata1799510.zip
      sudo rm chaindata1799510.zip
      echo "Back to Compiled QT Binary Folder"
      cd ~/denarius
      sudo echo "Get Coinexplorer FS List"
      sudo wget http://www.coinexplorer.net/api/v1/D/masternode/list
      sudo cat list | jq '.result[0].addr' | tr -d "\""  >> fspeers.txt
      sudo cat list | jq '.result[1].addr' | tr -d "\""  >> fspeers.txt
      sudo cat list | jq '.result[2].addr' | tr -d "\""  >> fspeers.txt
      sudo sed 's/^/addnode=/' fspeers.txt > addnode.txt
      sudo cat addnode.txt >> ~/.denarius/denarius.conf
      sudo rm list
      sudo rm fspeers.txt
      sudo rm addnode.txt
      qmake "USE_UPNP=1" "USE_QRCODE=1" OPENSSL_INCLUDE_PATH=/usr/local/ssl/include OPENSSL_LIB_PATH=/usr/local/ssl/lib denarius-qt.pro
      OPENSSL_INCLUDE_PATH=/usr/local/ssl/include OPENSSL_LIB_PATH=/usr/local/ssl/lib make -j4
